<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>blt</string>
   </array>
  <key>name</key>
  <string>blt</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.blt</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(^\s*\#\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\.\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.section task.default.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*x\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag task.complete.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\^\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string task.pushed.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\o\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable task.event.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\-\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.italic task.note.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__6</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\*\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>invalid.illegal task.important.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__7</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\&gt;\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.definition.tag task.delegated.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__8</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*\!\s)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function task.inspiration.blt</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__9</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>markup.heading task.header.blt</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>inline_types</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\s@\S*)</string>
          <key>name</key>
          <string>keyword.control.default task.detail.mention.blt</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s~\S*)</string>
          <key>name</key>
          <string>support.class.component task.detail.date.blt</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\s#\S*)</string>
          <key>name</key>
          <string>comment task.detail.tag.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>markup.heading task.header.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>entity.name.section task.default.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>punctuation.definition.tag task.complete.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>string task.pushed.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>variable task.event.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__6</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>markup.italic task.note.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__7</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>invalid.illegal task.important.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__8</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>punctuation.definition.tag task.delegated.blt</string>
        </dict>
       </array>
    </dict>
    <key>main__9</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#inline_types</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(.*?)(?=\s[\x{0040}\x{0023}\x{007e}]\S|$)</string>
          <key>name</key>
          <string>entity.name.function task.inspiration.blt</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
